apiVersion: apps/v1
kind: Deployment
metadata:
  name: chord-fe
  labels:
    app: chord-fe
spec:
  replicas: 25
  selector: 
    matchLabels:
      app: chord-fe
  template:
    metadata:
      labels:
        app: chord-fe
      annotations:
        restartedAt: ""
    spec:
      containers:
      - name: chord-fe
        image: pw1124/chord:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

# to create `regcred`, you need a dockerhub account,
# and then run: `kubectl create secret generic regcred \
#                  --from-file=.dockerconfigjson=[path/to/.docker/config.json] \
#                  --type=kubernetes.io/dockerconfigjson`
#
# you can then inspect it by: `kubectl get secret regcred \
#                                --output="jsonpath={.data.\.dockerconfigjson}" | base64 –decode
