name: Docker Image CI

on:
  push:
    branches:
      - master
    
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get current date
        id: date
        run: echo "::set-env name=date::$(TZ='America/Vancouver' date +%Y%h%d-%H-%M)"
      - name: Build image w/date label
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/chord:release-${{ env.date }}
      - name: Build image latest
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/chord:latest
      - name: Push image w/date label
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chord:release-${{ env.date }}
      - name: Push image latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chord:latest

