name: PR Test

on: [pull_request]

jobs:
    build:
        name: Verify Build
        runs-on: ubuntu-latest
        # runs-on: cluster-runner
        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies (lib-ssl, yarn, nodejs v15.x)
              run: bash ./.github/scripts/install-deps.sh

            - name: Install Dependencies
              run: yarn

            - name: Build
              run: yarn build
    test:
        name: Test
        # runs-on: ubuntu-latest
        runs-on: cluster-runner
        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies (lib-ssl, yarn, nodejs v15.x)
              run: bash ./.github/scripts/install-deps.sh

            - name: Install Dependencies
              run: yarn

            - name: Test
              run: yarn test --watchAll=false
    compile:
        name: Compile all sources
        # runs-on: ubuntu-latest
        runs-on: cluster-runner
        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies (lib-ssl, yarn, nodejs v15.x)
              run: bash ./.github/scripts/install-deps.sh

            - name: Install Dependencies
              run: yarn

            - name: Compile
              uses: icrawl/action-tsc@v1
