name: Deploy Production to Github Pages

on:
    push:
        branches:
            - master

jobs:
    publish:
        name: Publish master to Github Pages
        runs-on: ubuntu-22.04
        # runs-on: cluster-runner
        steps:
            # Checkout with history (to get git describe output properly)
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Update GIT-VERSION-FILE
              run: bash git-version.sh

            - name: Get version tag from GIT-VERSION-FILE
              run: echo "gitver=$(cat GIT-VERSION-FILE)" >> $GITHUB_ENV

            - name: Install Dependencies (lib-ssl, yarn, nodejs v15.x)
              run: bash ./.github/scripts/install-deps.sh

            - name: Install Dependencies
              run: yarn

            - name: Build
              run: REACT_APP_VERSION=${{ env.gitver }} yarn build-github-pages

            - name: Push to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3.6.1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
