name: Build New Runner Image

# this workflow only runs when there's a change in the .github/runner/ folder on the master branch.
on:
    push:
        branches:
            - master
        paths:
            - '.github/runner/**'

jobs:
    push:
        # runs-on: ubuntu-latest
        runs-on: chord-paper-fe-runner
        steps:
            # Checkout with history (to get git describe output properly)
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            # Run script, updates the GIT-VERSION-FILE with version number
            - name: Update GIT-VERSION-FILE
              run: bash git-version.sh
            - name: Get version tag from GIT-VERSION-FILE
              run: echo "gitver=$(cat GIT-VERSION-FILE)" >> $GITHUB_ENV
            - name: Login to DockerHub
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            - name: Build image w/version
              run: docker build ./.github/runner/ --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/chord-fe-runner:${{ env.gitver }}
            - name: Build image latest
              run: docker build ./.github/runner/ --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/chord-fe-runner:latest
            - name: Push image w/version
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chord-fe-runner:${{ env.gitver }}
            - name: Push image latest
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chord-fe-runner:latest
            - name: Get Current Timestamp
              run: echo "date=$(date +%s)" >> $GITHUB_ENV
